-- US Colleges and Universities
-- This script adds major US colleges and universities to the schools table
-- and adds college-level subjects to the subjects table

-- Insert US Colleges and Universities (Top 200+ institutions)
INSERT INTO schools (name) VALUES
-- Ivy League
('Harvard University'),
('Yale University'),
('Princeton University'),
('Columbia University'),
('University of Pennsylvania'),
('Brown University'),
('Dartmouth College'),
('Cornell University'),

-- Top Public Universities
('University of California, Berkeley'),
('University of California, Los Angeles'),
('University of Michigan'),
('University of Virginia'),
('University of North Carolina at Chapel Hill'),
('Georgia Institute of Technology'),
('University of Florida'),
('University of Texas at Austin'),
('University of Wisconsin-Madison'),
('University of Illinois at Urbana-Champaign'),
('University of Washington'),
('Ohio State University'),
('Penn State University'),
('Purdue University'),
('Texas A&M University'),
('University of Maryland, College Park'),
('University of Minnesota'),
('University of Georgia'),
('University of California, San Diego'),
('University of California, Irvine'),
('University of California, Santa Barbara'),
('University of California, Davis'),
('University of California, Riverside'),
('University of California, Santa Cruz'),
('University of California, Merced'),

-- Top Private Universities
('Stanford University'),
('Massachusetts Institute of Technology'),
('Duke University'),
('Northwestern University'),
('Johns Hopkins University'),
('University of Chicago'),
('California Institute of Technology'),
('Vanderbilt University'),
('Rice University'),
('Washington University in St. Louis'),
('Emory University'),
('Georgetown University'),
('Carnegie Mellon University'),
('University of Southern California'),
('Wake Forest University'),
('Tufts University'),
('Boston College'),
('New York University'),
('University of Rochester'),
('Brandeis University'),
('Case Western Reserve University'),
('Tulane University'),
('Boston University'),
('Northeastern University'),
('Lehigh University'),
('Syracuse University'),
('University of Miami'),
('Pepperdine University'),
('Southern Methodist University'),
('Rensselaer Polytechnic Institute'),

-- State Universities
('University of Alabama'),
('Arizona State University'),
('University of Arizona'),
('University of Arkansas'),
('University of Colorado Boulder'),
('University of Connecticut'),
('University of Delaware'),
('University of Hawaii'),
('University of Idaho'),
('University of Iowa'),
('University of Kansas'),
('University of Kentucky'),
('Louisiana State University'),
('University of Maine'),
('University of Massachusetts Amherst'),
('Michigan State University'),
('University of Mississippi'),
('University of Missouri'),
('University of Montana'),
('University of Nebraska-Lincoln'),
('University of Nevada, Las Vegas'),
('University of New Hampshire'),
('Rutgers University'),
('University of New Mexico'),
('SUNY Buffalo'),
('SUNY Stony Brook'),
('SUNY Binghamton'),
('University of North Dakota'),
('University of Oklahoma'),
('Oregon State University'),
('University of Oregon'),
('University of Rhode Island'),
('University of South Carolina'),
('University of South Dakota'),
('University of Tennessee'),
('University of Utah'),
('University of Vermont'),
('Virginia Tech'),
('University of West Virginia'),
('University of Wyoming'),

-- Liberal Arts Colleges
('Williams College'),
('Amherst College'),
('Swarthmore College'),
('Wellesley College'),
('Bowdoin College'),
('Carleton College'),
('Pomona College'),
('Claremont McKenna College'),
('Davidson College'),
('Haverford College'),
('Grinnell College'),
('Vassar College'),
('Colgate University'),
('Hamilton College'),
('Harvey Mudd College'),
('Middlebury College'),
('Wesleyan University'),
('Colby College'),
('Bates College'),
('Smith College'),
('Barnard College'),
('Oberlin College'),
('Washington and Lee University'),
('Macalester College'),
('Bryn Mawr College'),
('Mount Holyoke College'),
('Colorado College'),
('Kenyon College'),
('Reed College'),
('Scripps College'),

-- Technology and Engineering Schools
('Georgia Institute of Technology'),
('Massachusetts Institute of Technology'),
('California Institute of Technology'),
('Carnegie Mellon University'),
('Harvey Mudd College'),
('Rose-Hulman Institute of Technology'),
('Stevens Institute of Technology'),
('Worcester Polytechnic Institute'),
('Illinois Institute of Technology'),
('Kettering University'),
('Rochester Institute of Technology'),

-- Business Schools
('Wharton School (UPenn)'),
('Harvard Business School'),
('Stanford Graduate School of Business'),
('MIT Sloan School of Management'),
('Kellogg School of Management (Northwestern)'),
('Booth School of Business (University of Chicago)'),
('Haas School of Business (UC Berkeley)'),
('Columbia Business School'),
('Stern School of Business (NYU)'),
('Ross School of Business (University of Michigan)'),

-- Art and Music Schools
('Juilliard School'),
('Rhode Island School of Design'),
('Berklee College of Music'),
('School of the Art Institute of Chicago'),
('Pratt Institute'),
('Parsons School of Design'),
('California Institute of the Arts'),
('Cooper Union'),
('Savannah College of Art and Design'),

-- Medical Schools
('Johns Hopkins School of Medicine'),
('Harvard Medical School'),
('Stanford School of Medicine'),
('UCSF School of Medicine'),
('Mayo Clinic Alix School of Medicine'),
('Duke School of Medicine'),
('Washington University School of Medicine'),

-- Historically Black Colleges and Universities (HBCUs)
('Howard University'),
('Spelman College'),
('Morehouse College'),
('Hampton University'),
('Tuskegee University'),
('North Carolina A&T State University'),
('Florida A&M University'),
('Xavier University of Louisiana'),
('Fisk University'),
('Clark Atlanta University'),
('Morgan State University'),
('Tennessee State University'),
('Alabama State University'),
('Jackson State University'),
('Prairie View A&M University'),
('Southern University'),
('Norfolk State University'),
('Bethune-Cookman University'),
('Grambling State University'),
('Lincoln University'),

-- Additional Major Universities
('American University'),
('Auburn University'),
('Baylor University'),
('Brigham Young University'),
('Clemson University'),
('College of William & Mary'),
('Colorado State University'),
('Drexel University'),
('Florida State University'),
('Fordham University'),
('George Washington University'),
('Indiana University Bloomington'),
('Iowa State University'),
('Kansas State University'),
('Loyola University Chicago'),
('Marquette University'),
('Mississippi State University'),
('North Carolina State University'),
('Oklahoma State University'),
('Pitzer College'),
('San Diego State University'),
('Santa Clara University'),
('Seattle University'),
('Temple University'),
('University of Denver'),
('University of Notre Dame'),
('University of Pittsburgh'),
('University of San Diego'),
('Villanova University'),
('Wake Forest University')

ON CONFLICT (name) DO NOTHING;

-- Insert College-Level Subjects
INSERT INTO subjects (name) VALUES
-- Core Academic Subjects
('General Chemistry'),
('Organic Chemistry'),
('Biochemistry'),
('Physical Chemistry'),
('Analytical Chemistry'),
('Inorganic Chemistry'),

('General Physics'),
('Classical Mechanics'),
('Electromagnetism'),
('Quantum Mechanics'),
('Thermodynamics'),
('Statistical Mechanics'),
('Optics'),
('Condensed Matter Physics'),
('Nuclear Physics'),
('Particle Physics'),
('Astrophysics'),

('Calculus I'),
('Calculus II'),
('Calculus III'),
('Multivariable Calculus'),
('Linear Algebra'),
('Differential Equations'),
('Real Analysis'),
('Complex Analysis'),
('Abstract Algebra'),
('Number Theory'),
('Topology'),
('Probability Theory'),
('Statistics'),
('Discrete Mathematics'),
('Mathematical Logic'),
('Numerical Analysis'),

('Molecular Biology'),
('Cell Biology'),
('Genetics'),
('Evolution'),
('Ecology'),
('Developmental Biology'),
('Neuroscience'),
('Immunology'),
('Microbiology'),
('Anatomy'),
('Physiology'),
('Botany'),
('Zoology'),
('Marine Biology'),
('Bioinformatics'),

-- Computer Science
('Introduction to Programming'),
('Data Structures'),
('Algorithms'),
('Computer Architecture'),
('Operating Systems'),
('Database Systems'),
('Computer Networks'),
('Software Engineering'),
('Web Development'),
('Mobile Development'),
('Artificial Intelligence'),
('Machine Learning'),
('Deep Learning'),
('Natural Language Processing'),
('Computer Vision'),
('Computer Graphics'),
('Cybersecurity'),
('Cryptography'),
('Distributed Systems'),
('Cloud Computing'),
('Human-Computer Interaction'),
('Theory of Computation'),
('Compilers'),

-- Engineering
('Engineering Mechanics'),
('Thermodynamics'),
('Fluid Mechanics'),
('Heat Transfer'),
('Materials Science'),
('Statics'),
('Dynamics'),
('Electrical Circuits'),
('Electronics'),
('Digital Logic Design'),
('Signal Processing'),
('Control Systems'),
('Power Systems'),
('Electromagnetics'),
('Semiconductor Devices'),
('VLSI Design'),
('Mechanical Design'),
('Manufacturing Processes'),
('Robotics'),
('Aerospace Engineering'),
('Civil Engineering'),
('Environmental Engineering'),
('Chemical Engineering'),
('Biomedical Engineering'),
('Industrial Engineering'),

-- Business and Economics
('Microeconomics'),
('Macroeconomics'),
('Econometrics'),
('Game Theory'),
('International Economics'),
('Development Economics'),
('Labor Economics'),
('Public Economics'),
('Financial Accounting'),
('Managerial Accounting'),
('Corporate Finance'),
('Investment Analysis'),
('Financial Markets'),
('Derivatives'),
('Portfolio Management'),
('Marketing Management'),
('Operations Management'),
('Strategic Management'),
('Organizational Behavior'),
('Business Ethics'),
('Entrepreneurship'),
('Business Law'),
('International Business'),

-- Social Sciences
('Introduction to Psychology'),
('Cognitive Psychology'),
('Developmental Psychology'),
('Social Psychology'),
('Abnormal Psychology'),
('Clinical Psychology'),
('Behavioral Neuroscience'),
('Introduction to Sociology'),
('Social Theory'),
('Research Methods'),
('Criminology'),
('Urban Sociology'),
('Race and Ethnicity'),
('Gender Studies'),
('Political Science'),
('International Relations'),
('Comparative Politics'),
('American Government'),
('Political Theory'),
('Public Policy'),
('Anthropology'),
('Cultural Anthropology'),
('Archaeology'),
('Linguistic Anthropology'),

-- Humanities
('Western Civilization'),
('American History'),
('European History'),
('World History'),
('Ancient History'),
('Medieval History'),
('Modern History'),
('Art History'),
('Renaissance Art'),
('Modern Art'),
('Contemporary Art'),
('Philosophy'),
('Ethics'),
('Logic'),
('Metaphysics'),
('Epistemology'),
('Political Philosophy'),
('Philosophy of Mind'),
('Philosophy of Science'),
('Existentialism'),
('American Literature'),
('British Literature'),
('World Literature'),
('Creative Writing'),
('Poetry'),
('Fiction Writing'),
('Screenwriting'),
('Journalism'),
('Media Studies'),
('Film Studies'),
('Theater'),
('Music Theory'),
('Music History'),
('Composition'),

-- Languages
('Spanish'),
('French'),
('German'),
('Italian'),
('Portuguese'),
('Russian'),
('Chinese (Mandarin)'),
('Japanese'),
('Korean'),
('Arabic'),
('Hebrew'),
('Latin'),
('Ancient Greek'),
('Hindi'),
('Sanskrit'),

-- Health Sciences
('Human Anatomy'),
('Human Physiology'),
('Pathology'),
('Pharmacology'),
('Toxicology'),
('Epidemiology'),
('Public Health'),
('Nutrition'),
('Kinesiology'),
('Exercise Physiology'),
('Sports Medicine'),
('Nursing Fundamentals'),
('Medical Ethics'),

-- Law
('Constitutional Law'),
('Criminal Law'),
('Civil Procedure'),
('Contracts'),
('Torts'),
('Property Law'),
('Corporate Law'),
('Tax Law'),
('Environmental Law'),
('Intellectual Property Law'),

-- Architecture and Design
('Architectural Design'),
('Urban Planning'),
('Landscape Architecture'),
('Interior Design'),
('Graphic Design'),
('Industrial Design'),
('Fashion Design'),
('Product Design'),

-- Education
('Educational Psychology'),
('Curriculum and Instruction'),
('Special Education'),
('Educational Technology'),
('Literacy Education'),

-- Environmental Science
('Environmental Science'),
('Climate Change'),
('Conservation Biology'),
('Sustainability'),
('Renewable Energy'),

-- Agriculture
('Agronomy'),
('Animal Science'),
('Food Science'),
('Agricultural Economics'),

-- Communication
('Public Speaking'),
('Rhetoric'),
('Mass Communication'),
('Interpersonal Communication'),
('Organizational Communication')

ON CONFLICT (name) DO NOTHING;

-- Note: This script uses ON CONFLICT DO NOTHING to avoid duplicate entries
-- Run this in your Supabase SQL Editor
