name: Apply Supabase SQL

on:
  workflow_dispatch:
    inputs:
      sql_file:
        description: Path to SQL file to run
        required: false
        default: study-resources/CRITICAL_DATABASE_SETUP.sql

jobs:
  apply-sql:
    runs-on: ubuntu-latest
    env:
      PROJECT_REF: dnknanwmaekhtmpbpjpo
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Read SQL file
        id: sql
        run: |
          FILE="${{ github.event.inputs.sql_file }}"
          if [ -z "$FILE" ]; then FILE="study-resources/CRITICAL_DATABASE_SETUP.sql"; fi
          echo "Using SQL file: $FILE"
          SQL_JSON=$(jq -Rs . < "$FILE")
          echo "sql_json=$SQL_JSON" >> $GITHUB_OUTPUT

      - name: Run SQL via Supabase Management API
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then
            echo "Missing SUPABASE_ACCESS_TOKEN secret. Create a PAT at https://supabase.com/dashboard/account/tokens and add it to repo secrets." >&2
            exit 1
          fi
          curl -sS -X POST \
            -H "Authorization: Bearer $SUPABASE_ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"query\": ${{ steps.sql.outputs.sql_json }} }" \
            https://api.supabase.com/v1/projects/${PROJECT_REF}/sql | tee response.json

      - name: Show response
        run: |
          cat response.json
